"""Prompt templates for the skill-discovery pipeline."""

from prompts.clustering import (
    SUMMARISE_FAILURE_PROMPT,
    SUMMARISE_SUCCESS_PROMPT,
)
from prompts.induction import (
    CONTEXTUAL_ABSTRACT_SYSTEM,
    CONTEXTUAL_ABSTRACT_PROMPT,
    FAILURE_PATTERN_SYSTEM,
    FAILURE_PATTERN_PROMPT,
    SUCCESS_PATTERN_SYSTEM,
    SUCCESS_PATTERN_PROMPT,
    CONTRASTIVE_SYSTEM,
    CONTRASTIVE_PROMPT,
)
from prompts.generation import (
    GENERATE_PLAN_SYSTEM,
    GENERATE_PLAN_PROMPT,
    GENERATE_EXEC_SYSTEM,
    GENERATE_EXEC_PROMPT,
    DECOMPOSE_SYSTEM,
    DECOMPOSE_PROMPT,
    GEN_SCRIPT_SYSTEM,
    GEN_SCRIPT_PROMPT,
    GEN_REFERENCE_SYSTEM,
    GEN_REFERENCE_PROMPT,
    COMPOSE_BODY_SYSTEM,
    COMPOSE_BODY_PROMPT,
)
from prompts.verification import (
    CASE_ANALYSIS_SYSTEM,
    CASE_ANALYSIS_PROMPT,
    REVISION_SYNTHESIS_SYSTEM,
    REVISION_SYNTHESIS_PROMPT,
    REFINE_SYSTEM,
    REFINE_PROMPT,
)
from prompts.trajectory import (
    EVALUATE_SYSTEM,
    EVALUATE_PROMPT,
    AGENT_SYSTEM,
    AGENT_SYSTEM_WITH_TOOLS,
    AGENT_PROMPT,
    SKILL_SECTION_TEMPLATE,
)
from prompts.router import (
    SKILL_ROUTER_SYSTEM,
    SKILL_ROUTER_PROMPT,
    SKILL_SELECT_SYSTEM,
    SKILL_SELECT_PROMPT,
)

__all__ = [
    # clustering
    "SUMMARISE_FAILURE_PROMPT",
    "SUMMARISE_SUCCESS_PROMPT",
    # induction
    "CONTEXTUAL_ABSTRACT_SYSTEM",
    "CONTEXTUAL_ABSTRACT_PROMPT",
    "FAILURE_PATTERN_SYSTEM",
    "FAILURE_PATTERN_PROMPT",
    "SUCCESS_PATTERN_SYSTEM",
    "SUCCESS_PATTERN_PROMPT",
    "CONTRASTIVE_SYSTEM",
    "CONTRASTIVE_PROMPT",
    # generation
    "GENERATE_PLAN_SYSTEM",
    "GENERATE_PLAN_PROMPT",
    "GENERATE_EXEC_SYSTEM",
    "GENERATE_EXEC_PROMPT",
    "DECOMPOSE_SYSTEM",
    "DECOMPOSE_PROMPT",
    "GEN_SCRIPT_SYSTEM",
    "GEN_SCRIPT_PROMPT",
    "GEN_REFERENCE_SYSTEM",
    "GEN_REFERENCE_PROMPT",
    "COMPOSE_BODY_SYSTEM",
    "COMPOSE_BODY_PROMPT",
    # verification
    "CASE_ANALYSIS_SYSTEM",
    "CASE_ANALYSIS_PROMPT",
    "REVISION_SYNTHESIS_SYSTEM",
    "REVISION_SYNTHESIS_PROMPT",
    "REFINE_SYSTEM",
    "REFINE_PROMPT",
    # trajectory / agent runner
    "EVALUATE_SYSTEM",
    "EVALUATE_PROMPT",
    "AGENT_SYSTEM",
    "AGENT_SYSTEM_WITH_TOOLS",
    "AGENT_PROMPT",
    "SKILL_SECTION_TEMPLATE",
    # router
    "SKILL_ROUTER_SYSTEM",
    "SKILL_ROUTER_PROMPT",
    "SKILL_SELECT_SYSTEM",
    "SKILL_SELECT_PROMPT",
]
